.TH "Stm32doxin/Core/Src/main.c" 3 "StmDoxin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Stm32doxin/Core/Src/main.c \- : Main program body  

.SH SYNOPSIS
.br
.PP
\fR#include 'main\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBSystemClock_Config\fP (void)"
.br
.RI "System Clock Configuration\&. "
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.RI "The application entry point\&. "
.ti -1c
.RI "void \fBError_Handler\fP (void)"
.br
.RI "This function is executed in case of error occurrence\&. "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAttention\fP
.RS 4

.RE
.PP
Copyright (c) 2025 STMicroelectronics\&. All rights reserved\&.

.PP
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component\&. If no LICENSE file comes with this software, it is provided AS-IS\&. 
.SH "Function Documentation"
.PP 
.SS "void Error_Handler (void )"

.PP
\fBReturn values\fP
.RS 4
\fINone\fP 
.RE
.PP

.SS "int main (void )"

.PP
\fBReturn values\fP
.RS 4
\fIint\fP 
.RE
.PP

.SS "void SystemClock_Config (void )"

.PP
\fBReturn values\fP
.RS 4
\fINone\fP 
.RE
.PP
Supply configuration update enable

.PP
Configure the main internal regulator output voltage

.PP
Initializes the RCC Oscillators according to the specified parameters in the RCC_OscInitTypeDef structure\&.

.PP
Initializes the CPU, AHB and APB buses clocks
.SH "Author"
.PP 
Generated automatically by Doxygen for StmDoxin from the source code\&.
