.TH "Stm32doxin/Core/Src/stm32h7xx_it.c" 3 "StmDoxin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Stm32doxin/Core/Src/stm32h7xx_it.c \- Interrupt Service Routines\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'main\&.h'\fP
.br
\fR#include 'stm32h7xx_it\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBNMI_Handler\fP (void)"
.br
.RI "This function handles Non maskable interrupt\&. "
.ti -1c
.RI "void \fBHardFault_Handler\fP (void)"
.br
.RI "This function handles Hard fault interrupt\&. "
.ti -1c
.RI "void \fBMemManage_Handler\fP (void)"
.br
.RI "This function handles Memory management fault\&. "
.ti -1c
.RI "void \fBBusFault_Handler\fP (void)"
.br
.RI "This function handles Pre-fetch fault, memory access fault\&. "
.ti -1c
.RI "void \fBUsageFault_Handler\fP (void)"
.br
.RI "This function handles Undefined instruction or illegal state\&. "
.ti -1c
.RI "void \fBSVC_Handler\fP (void)"
.br
.RI "This function handles System service call via SWI instruction\&. "
.ti -1c
.RI "void \fBDebugMon_Handler\fP (void)"
.br
.RI "This function handles Debug monitor\&. "
.ti -1c
.RI "void \fBPendSV_Handler\fP (void)"
.br
.RI "This function handles Pendable request for system service\&. "
.ti -1c
.RI "void \fBSysTick_Handler\fP (void)"
.br
.RI "This function handles System tick timer\&. "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAttention\fP
.RS 4

.RE
.PP
Copyright (c) 2025 STMicroelectronics\&. All rights reserved\&.

.PP
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component\&. If no LICENSE file comes with this software, it is provided AS-IS\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for StmDoxin from the source code\&.
