.TH "STM32H7xx_System_Private_Variables" 3 "StmDoxin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
STM32H7xx_System_Private_Variables \- STM32H7xx_System_Private_Variables
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "uint32_t \fBSystemCoreClock\fP = 64000000"
.br
.ti -1c
.RI "uint32_t \fBSystemD2Clock\fP = 64000000"
.br
.ti -1c
.RI "const uint8_t \fBD1CorePrescTable\fP [16] = {0, 0, 0, 0, 1, 2, 3, 4, 1, 2, 3, 4, 6, 7, 8, 9}"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for StmDoxin from the source code\&.
