.TH "Stm32doxin/Core/Src/system_stm32h7xx.c" 3 "StmDoxin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Stm32doxin/Core/Src/system_stm32h7xx.c \- CMSIS Cortex-Mx Device Peripheral Access Layer System Source File\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'stm32h7xx\&.h'\fP
.br
\fR#include <math\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHSE_VALUE\fP   ((uint32_t)25000000)"
.br
.ti -1c
.RI "#define \fBCSI_VALUE\fP   ((uint32_t)4000000)"
.br
.ti -1c
.RI "#define \fBHSI_VALUE\fP   ((uint32_t)64000000)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBSystemInit\fP (void)"
.br
.RI "Setup the microcontroller system Initialize the FPU setting and vector table location configuration\&. "
.ti -1c
.RI "void \fBSystemCoreClockUpdate\fP (void)"
.br
.RI "Update SystemCoreClock variable according to Clock Register Values\&. The SystemCoreClock variable contains the core clock , it can be used by the user application to setup the SysTick timer or configure other parameters\&. "
.ti -1c
.RI "void \fBExitRun0Mode\fP (void)"
.br
.RI "Exit Run* mode and Configure the system Power Supply\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "uint32_t \fBSystemCoreClock\fP = 64000000"
.br
.ti -1c
.RI "uint32_t \fBSystemD2Clock\fP = 64000000"
.br
.ti -1c
.RI "const uint8_t \fBD1CorePrescTable\fP [16] = {0, 0, 0, 0, 1, 2, 3, 4, 1, 2, 3, 4, 6, 7, 8, 9}"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
MCD Application Team 
.RE
.PP
This file provides two functions and one global variable to be called from user application:
.IP "\(bu" 2
\fBExitRun0Mode()\fP: Specifies the Power Supply source\&. This function is called at startup just after reset and before the call of \fBSystemInit()\fP\&. This call is made inside the "startup_stm32h7xx\&.s" file\&.
.IP "\(bu" 2
\fBSystemInit()\fP: This function is called at startup just after reset and before branch to main program\&. This call is made inside the "startup_stm32h7xx\&.s" file\&.
.IP "\(bu" 2
SystemCoreClock variable: Contains the core clock, it can be used by the user application to setup the SysTick timer or configure other parameters\&.
.IP "\(bu" 2
\fBSystemCoreClockUpdate()\fP: Updates the variable SystemCoreClock and must be called whenever the core clock is changed during program execution\&.
.PP

.PP
\fBAttention\fP
.RS 4
.RE
.PP
Copyright (c) 2017 STMicroelectronics\&. All rights reserved\&.

.PP
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component\&. If no LICENSE file comes with this software, it is provided AS-IS\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for StmDoxin from the source code\&.
